name: arr-stack_recyclar

#########################
# Centralized Volumes   #
#########################
volumes:
  recyclarr-data:

#########################
# Networks              #
#########################
networks:
  arr-stack:
    external: true

#########################
# Logging               #
#########################
x-logging: &default-logging
  driver: "json-file"
  options:
    max-size: "10m"
    max-file: "3"

#########################
# Services              #
#########################
services:
  # ═══════════════════════════════════════════════════════════════════════════
  # RECYCLARR - Subtitle manager. Automatically downloads subtitles.
  # Access: recyclarr.lan | recyclarr.yourdomain.com | NAS_IP:
  # ═══════════════════════════════════════════════════════════════════════════
  recyclarr:
    image: ghcr.io/recyclarr/recyclarr
    container_name: recyclarr
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: ${TZ}
    networks:
      - arr-stack
    volumes:
      - ./recyclarr:/config
      - recyclarr-data:/data
    labels:
      - deunhealth.restart.on.unhealthy=true
    restart: unless-stopped
    logging: *default-logging